// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZuYgaFD_P7ulsZV1x2yWWPJ5tTRyxZ4',
    appId: '1:331746479659:android:fe8118b19bfc1c4a5f646e',
    messagingSenderId: '331746479659',
    projectId: 'chatapp-e8fd8',
    storageBucket: 'chatapp-e8fd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECONeWu9ZObZnryIAJi-YDZyASFY8sSU',
    appId: '1:331746479659:ios:8d7adf276307beef5f646e',
    messagingSenderId: '331746479659',
    projectId: 'chatapp-e8fd8',
    storageBucket: 'chatapp-e8fd8.appspot.com',
    androidClientId: '331746479659-9bn5cgped88tl82ha4d1qu060ci17loo.apps.googleusercontent.com',
    iosClientId: '331746479659-nd7d4jjge264ebk9hntj27t5jpdokl0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}